# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: be061237096c1f9c496dd6b16bd1edcbc5461ee62566848d91858e4f82769ef265f5eef889d935b38f3fae4aa774712b935b1ce17c94b9ce09e449508cd480d0

test:
  secret_key_base: 376f3a7e74c4667b580dcb234e559bf1e9ae9c10c788eb62d988c347d3862d6f8df29f38cf122dcf25d6c8fa18547f808dc8ace54a758af4ea315d0190a7fdb9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
